#!/bin/bash

id_gal=""
start="adb -s 4790201fe8dbafae shell am start -a android.intent.action.VIEW -t image/jpg -d file:///storage//sdcard0//jpg_sample//1.jpg"

restarted=0

# Check if gallery application is still running or if a crash occurred                           
 
function check_gallery {
    i=$(adb -s 4790201fe8dbafae shell ps | grep com.sec.android.gallery3d)
    id=$(echo $i | cut -d " " -f 2)

    if [ "$id" != "" ] ;then
        echo "Gallery running with pid $id"
	if [ "$id" != "$id_gal" ] ; then
            echo $id_gal
            echo "Gallery restarted with pid $id"
            restarted=1
        fi;
    else
        echo "Gallery not running\n Restarting....\n"
        $start
        adb -s 4790201fe8dbafae shell input keyevent 4
        i=$(adb -s 4790201fe8dbafae shell ps | grep com.sec.android.gallery3d)
        id=$(echo $i | cut -d " " -f 2)
	restarted=1
        echo "Gallery restarted with pid $id...\n"
        sleep 2
    fi;
    id_gal=$id
}


# Check the state of the process and wait until sleeping is reached                                
function check_state {
    for i in `seq 0 10`; do
        state=$(adb -s 4790201fe8dbafae shell cat /proc/$id_gal/status | grep State)
        get_state=$(echo $state | cut -d " " -f 2)
        if [ "$get_state" != "S" ]; then
            echo "Not finished yet... "
            sleep $1
        fi;
    done;
}




function wait_for_crash {
    for i in `seq 1 10`;
    do
	p=$(adb -s 4790201fe8dbafae shell ps | grep gal)
	echo $p
	if [ "$p" == "" ]; then
	    print $p
	    return
	fi;
	sleep 1
    done;
    i=$(adb -s 4790201fe8dbafae shell ps | grep com.sec.android.gallery3d)
    id=$(echo $i | cut -d " " -f 2)
    adb -s 4790201fe8dbafae shell su -c kill -9 $id
}

c=0
check_gallery
while [ 1 ] ; 
do
    check_gallery
    radamsa ~/jpg/jpg_ok/* > fuzzed.jpg
    adb -s 4790201fe8dbafae push fuzzed.jpg /sdcard/fuzzed.jpg
    adb -s 4790201fe8dbafae shell logcat -c
    adb -s 4790201fe8dbafae shell am start -a android.intent.action.VIEW -t image/jpg -d file:///storage//sdcard0//fuzzed.jpg
    sleep 0.2
    check_state 1
    crash=$(adb -s 4790201fe8dbafae shell su -c sh /data/local/tmp/crash_check)
    if [ "$crash" != "" ] || [ $restarted -eq 1 ]; then
    	echo "Crash detected!"
	cp ./fuzzed.jpg ./crashed/$c.jpg
	adb -s 4790201fe8dbafae shell "logcat -d > /sdcard/crash.log"
	adb -s 4790201fe8dbafae pull /sdcard/crash.log ./crashed/$c.log
	c=$(($c+1))
	restarted=0
    fi;
    adb -s 4790201fe8dbafae shell input keyevent 4
	

done
