#pragma once
/* This file is auto-generated by configure.sh */
#define USE_IPV6 1
#define USE_PPPOL2TPIN6 1
#define USE_PPPOL2TPV3 1
#define USE_PPPOX_PPTP 1
#define USE_LLC_OPT_PKTINFO 1
#define HAVE_TERMIOS2 1
#define USE_CAIF 1
#define USE_IF_ALG 1
#define USE_RDS 1
#define USE_VFIO 1
#define USE_BTRFS 1
#define USE_KVM 1
#define USE_SECCOMP 1
#define USE_VHOST 1
