// autogenerated file
#ifndef __HIJACKS_H__
#define __HIJACKS_H__
#include "hijack_func/nfc_jni_get_technology_tree.h"
#include "hijack_func/phDal4Nfc_i2c_reset.h"
#include "hijack_func/phDal4Nfc_msgrcv.h"
#include "hijack_func/phFriNfc_MifareStdMap_RdNdef.h"
#include "hijack_func/phLibNfc_Mgt_ConfigureDiscovery.h"
#include "hijack_func/phLibNfc_Ndef_CheckNdef.h"
#include "hijack_func/phLibNfc_Ndef_Read.h"
#include "hijack_func/phLibNfc_RemoteDev_CheckPresence.h"
#include "hijack_func/phLibNfc_RemoteDev_Connect.h"
#include "hijack_func/phLibNfc_RemoteDev_NtfRegister.h"
#endif
